#!/bin/bash
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

RED="\e[0;31m"
GREEN="\e[0;32m"
RESET="\e[0m"

c_files=$(git diff-index HEAD --name-only | grep "\\.[ch]$")

if [[ -n $c_files ]] && ! ./ci/build.sh; then
    printf "%bError:%b Failed to build." "$RED" "$RESET"
    exit 1
fi

for file in $c_files; do
    if ! clang-format -Werror --dry-run "$file" 2> /dev/null; then
        printf "%bError:%b Code should be formatted. Use:\n\n" "$RED" "$RESET"
        printf "  \$ %bclang-format%b -i -- **/*.c **/*.h\n" "$GREEN" "$RESET"

        exit 2
    fi
done
